#-------------------------------------------------------------#
# - Docker Compose file for the KonnektBox Telemetry Daemon - #
#-------------------------------------------------------------#


version: '3'
services:
  InternalBroker:
    image: eclipse-mosquitto:1.6.12
    ports:
      - "1883:1883"
      - "8083:8083"
    container_name: intBroker
    hostname: intBroker

  telemetry:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: konnektbox-telemetry
    container_name: telem
    network_mode: "host"
    hostname: telem
    environment:
      - MQTT_ID=telemetryELASTIC
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_PROTOCOL="tcp"
      - REST_PORT=8080
      - MONITOR_PERIOD=2
      - REPORT_PERIOD=2
      - CATEGORIES={"Active":["CPU", "Disk", "Mem", "Net"]}
      - PEER_LIST={"enp0s3":["8.8.4.4", "8.8.8.8"]}

  telegraf:
    image: telegraf:1.18-alpine
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.5.4
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
  influxdb:
